### ISSUE TITLE
[BUG] Weekly frequency dataset causes errors on validation

### ISSUE THREAD

**Issue by shamshaw** [neuralhydrology/neuralhydrology#111]
I was working on testing running a model on a weekly timestep dataset but am getting an error during validation that relates to that weekly frequency I think. 

I've tried prepping the dataset a couple ways - based on starting day (W-FRI) and then also a sunday week start (W-SUN) but both are erroring with the `ValueError: only leading negative signs are allowed`.

The model environment being used has been working fine for daily timestep predictions, but we are interested in doing an experiment at a weekly timestep. 

Is there a different preparation for weekly timestep data that would avoid raising that error? 

**Logs & Screenshots**
```
Traceback (most recent call last):
  File "run_neural_hydrology.py", line 179, in <module>
    start_run(config_file = config_file)
  File "/opt/ml/code/neuralhydrology/nh_run.py", line 76, in start_run
    start_training(config)
  File "/opt/ml/code/neuralhydrology/training/train.py", line 23, in start_training
    trainer.train_and_validate()
  File "/opt/ml/code/neuralhydrology/training/basetrainer.py", line 217, in train_and_validate
    self.validator.evaluate(epoch=epoch,
  File "/opt/ml/code/neuralhydrology/evaluation/tester.py", line 258, in evaluate
    'time_step': ((dates[freq][0, :] - dates[freq][0, -1]) / pd.Timedelta(freq)).astype(np.int64) +
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1344, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "pandas/_libs/tslibs/timedeltas.pyx", line 409, in pandas._libs.tslibs.timedeltas.parse_timedelta_string

ValueError: only leading negative signs are allowed
```

Running on v.1.4.0

**Comment by gauchm** [comment]
The reason for the exception is that `pd.Timedelta` doesn't support resolutions such as `W-FRI`. Could you try using `7D`?

**Comment by shamshaw** [comment]
Thanks @gauchm -- I'm not super familiar with pandas time frequencies. Where/how would you set the input data files to be recognized as 7D? Is that automatic based on the dates in the file? Or is that set in our dataset class?
