### ISSUE TITLE
[BUG] subprocess.CalledProcessError when I tried to train 1st tutorial

### ISSUE THREAD

**Issue by rogerzzl** [neuralhydrology/neuralhydrology#123]
Hi there, greatly thanks for your excellent codes for ML in Hydrology, I met a bug when I started.
**Describe the bug**
subprocess.CalledProcessError: Command '['git', '-C', '/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/utils', 'describe', '--always']' returned non-zero exit status 128.

**To Reproduce**
I'm doing the *01-Introduction/1_basin train* in MacOS Ventura, the *log* when I run *nh-run train --config-file 1_basin.yml* is as below.
```
2023-06-01 17:30:56,901: Logging to /Users/roger/Rogerr/PhD/VIC/LSTM/neuralhydrology-master/examples/01-Introduction/runs/test_run_0106_173056/output.log initialized.
2023-06-01 17:30:56,901: ### Folder structure created at /Users/roger/Rogerr/PhD/VIC/LSTM/neuralhydrology-master/examples/01-Introduction/runs/test_run_0106_173056
2023-06-01 17:30:56,901: ### Run configurations for test_run
2023-06-01 17:30:56,902: experiment_name: test_run
2023-06-01 17:30:56,902: train_basin_file: 1_basin.txt
2023-06-01 17:30:56,902: validation_basin_file: 1_basin.txt
2023-06-01 17:30:56,902: test_basin_file: 1_basin.txt
2023-06-01 17:30:56,902: train_start_date: 1999-10-01 00:00:00
2023-06-01 17:30:56,902: train_end_date: 2008-09-30 00:00:00
2023-06-01 17:30:56,902: validation_start_date: 1980-10-01 00:00:00
2023-06-01 17:30:56,902: validation_end_date: 1989-09-30 00:00:00
2023-06-01 17:30:56,902: test_start_date: 1989-10-01 00:00:00
2023-06-01 17:30:56,902: test_end_date: 1999-09-30 00:00:00
2023-06-01 17:30:56,902: device: cpu
2023-06-01 17:30:56,903: validate_every: 3
2023-06-01 17:30:56,903: validate_n_random_basins: 1
2023-06-01 17:30:56,903: metrics: ['NSE']
2023-06-01 17:30:56,903: model: CustomLSTM
2023-06-01 17:30:56,903: head: regression
2023-06-01 17:30:56,903: output_activation: linear
2023-06-01 17:30:56,903: hidden_size: 20
2023-06-01 17:30:56,903: initial_forget_bias: 3
2023-06-01 17:30:56,903: output_dropout: 0.4
2023-06-01 17:30:56,903: optimizer: Adam
2023-06-01 17:30:56,903: loss: MSE
2023-06-01 17:30:56,904: learning_rate: {0: 0.01, 30: 0.005, 40: 0.001}
2023-06-01 17:30:56,904: batch_size: 256
2023-06-01 17:30:56,904: epochs: 50
2023-06-01 17:30:56,904: clip_gradient_norm: 1
2023-06-01 17:30:56,904: predict_last_n: 1
2023-06-01 17:30:56,904: seq_length: 365
2023-06-01 17:30:56,904: num_workers: 8
2023-06-01 17:30:56,904: log_interval: 5
2023-06-01 17:30:56,904: log_tensorboard: True
2023-06-01 17:30:56,904: log_n_figures: 1
2023-06-01 17:30:56,904: save_weights_every: 1
2023-06-01 17:30:56,904: dataset: camels_us
2023-06-01 17:30:56,904: data_dir: /Volumes/T7_Shield/LSTM/CAMELS
2023-06-01 17:30:56,904: forcings: ['maurer', 'daymet', 'nldas']
2023-06-01 17:30:56,905: dynamic_inputs: ['PRCP(mm/day)_nldas', 'PRCP(mm/day)_maurer', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']
2023-06-01 17:30:56,905: target_variables: ['QObs(mm/d)']
2023-06-01 17:30:56,905: clip_targets_to_zero: ['QObs(mm/d)']
2023-06-01 17:30:56,905: number_of_basins: 1
2023-06-01 17:30:56,905: run_dir: /Users/roger/Rogerr/PhD/VIC/LSTM/neuralhydrology-master/examples/01-Introduction/runs/test_run_0106_173056
2023-06-01 17:30:56,905: train_dir: /Users/roger/Rogerr/PhD/VIC/LSTM/neuralhydrology-master/examples/01-Introduction/runs/test_run_0106_173056/train_data
2023-06-01 17:30:56,905: img_log_dir: /Users/roger/Rogerr/PhD/VIC/LSTM/neuralhydrology-master/examples/01-Introduction/runs/test_run_0106_173056/img_log
2023-06-01 17:30:56,907: ### Device cpu will be used for training
2023-06-01 17:30:56,908: Loading basin data into xarray data set.
100%|███████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.17it/s]
2023-06-01 17:30:57,388: Create lookup table and convert to pytorch tensor
100%|███████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
fatal: Not a valid object name HEAD
2023-06-01 17:30:59,038: Uncaught exception
Traceback (most recent call last):
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/bin/nh-run", line 8, in <module>
    sys.exit(_main())
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/nh_run.py", line 43, in _main
    start_run(config_file=Path(args["config_file"]), gpu=args["gpu"])
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/nh_run.py", line 76, in start_run
    start_training(config)
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/training/train.py", line 19, in start_training
    trainer.initialize_training()
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/training/basetrainer.py", line 175, in initialize_training
    self.experiment_logger = Logger(cfg=self.cfg)
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/training/logger.py", line 31, in __init__
    cfg.update_config({'commit_hash': get_git_hash()})
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/utils/logging_utils.py", line 45, in get_git_hash
    return subprocess.check_output(["git", "-C", current_dir, "describe", "--always"]).strip().decode('ascii')
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '-C', '/Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/utils', 'describe', '--always']' returned non-zero exit status 128.

```

**Desktop & Environment (please complete the following information):**
 - OS: *MacOS Ventura*
 - *__version__ = "1.7.0"*
 - As below
 ```
name: neuralhydrology
channels:
  - pytorch
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anyio=3.5.0=py310hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py310hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310hca72f7f_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310hecd8cb5_0
  - babel=2.11.0=py310hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py310hecd8cb5_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=3.1.1=py310h20db666_0
  - bottleneck=1.3.5=py310h4e76f89_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py310hca72f7f_1002
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.19.0=h6c40b1e_0
  - ca-certificates=2023.01.10=hecd8cb5_0
  - certifi=2023.5.7=py310hecd8cb5_0
  - cffi=1.15.1=py310h6c40b1e_3
  - cftime=1.6.2=py310h7b7cdfe_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py310hecd8cb5_0
  - comm=0.1.2=py310hecd8cb5_0
  - contourpy=1.0.5=py310haf03e11_0
  - coverage=7.2.2=py310h6c40b1e_0
  - cpuonly=2.0=0
  - cryptography=39.0.1=py310hf6deb26_0
  - curl=7.88.1=h6c40b1e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py310he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.18.1=py310hecd8cb5_3
  - entrypoints=0.4=py310hecd8cb5_0
  - exceptiongroup=1.0.4=py310hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.9.0=py310hecd8cb5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - gettext=0.21.0=he85b6c0_1
  - giflib=5.2.1=h6c40b1e_3
  - glib=2.69.1=hfff2838_2
  - gmp=6.2.1=he9d5cce_3
  - gmpy2=2.1.2=py310hd5de756_0
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - h5py=3.7.0=py310h6c517f8_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.6=h10fe05b_1
  - icu=58.2=h0a44026_3
  - idna=3.4=py310hecd8cb5_0
  - imagesize=1.4.1=py310hecd8cb5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.19.2=py310h20db666_0
  - ipython=8.12.0=py310hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py310hecd8cb5_0
  - jedi=0.18.1=py310hecd8cb5_1
  - jinja2=3.1.2=py310hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310hecd8cb5_0
  - jupyter=1.0.0=py310hecd8cb5_8
  - jupyter_client=8.1.0=py310hecd8cb5_0
  - jupyter_console=6.6.3=py310hecd8cb5_0
  - jupyter_core=5.3.0=py310hecd8cb5_0
  - jupyter_server=1.23.4=py310hecd8cb5_0
  - jupyterlab=3.5.3=py310hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py310hecd8cb5_0
  - jupyterlab_widgets=3.0.5=py310hecd8cb5_0
  - kiwisolver=1.4.4=py310hcec6c5f_0
  - krb5=1.19.4=hdba6334_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libclang=14.0.6=default_hd95374b_1
  - libclang13=14.0.6=default_habbcc1a_1
  - libcurl=7.88.1=ha585b31_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20221030=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.16=hca72f7f_2
  - libllvm14=14.0.6=h91fad77_3
  - libnetcdf=4.8.1=ha5d86b0_2
  - libnghttp2=1.46.0=ha29bfda_0
  - libpng=1.6.39=h6c40b1e_0
  - libpq=12.9=h1c9f633_3
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.10.0=h0a4fc7d_0
  - libtiff=4.5.0=hcec6c5f_2
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxml2=2.10.3=h930c0e2_0
  - libxslt=1.1.37=h6d1eb0e_0
  - libzip=1.8.0=h272c8d6_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - llvmlite=0.40.0=py310hfff2838_0
  - lxml=4.9.2=py310h6c40b1e_0
  - lz4-c=1.9.4=hcec6c5f_0
  - markupsafe=2.1.1=py310hca72f7f_0
  - matplotlib=3.7.1=py310hecd8cb5_1
  - matplotlib-base=3.7.1=py310ha533b9c_1
  - matplotlib-inline=0.1.6=py310hecd8cb5_0
  - mistune=0.8.4=py310hca72f7f_1000
  - mkl=2023.1.0=h59209a4_43558
  - mkl-service=2.4.0=py310h6c40b1e_1
  - mkl_fft=1.3.6=py310h3ea8b11_1
  - mkl_random=1.2.2=py310h3ea8b11_1
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py310hecd8cb5_0
  - nbclient=0.5.13=py310hecd8cb5_0
  - nbconvert=6.5.4=py310hecd8cb5_0
  - nbformat=5.7.0=py310hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py310hecd8cb5_0
  - netcdf4=1.6.2=py310h2f655f6_0
  - networkx=2.8.4=py310hecd8cb5_1
  - notebook=6.5.4=py310hecd8cb5_0
  - notebook-shim=0.2.2=py310hecd8cb5_0
  - nspr=4.35=hcec6c5f_0
  - nss=3.89.1=hcec6c5f_0
  - numba=0.57.0=py310h3ea8b11_0
  - numexpr=2.8.4=py310h827a554_1
  - numpy=1.24.3=py310h827a554_1
  - numpy-base=1.24.3=py310ha186be2_1
  - openssl=1.1.1t=hca72f7f_0
  - packaging=23.0=py310hecd8cb5_0
  - pandas=1.5.3=py310h3ea8b11_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310hcec6c5f_0
  - pip=23.0.1=py310hecd8cb5_0
  - platformdirs=2.5.2=py310hecd8cb5_0
  - pluggy=1.0.0=py310hecd8cb5_1
  - ply=3.11=py310hecd8cb5_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py310hecd8cb5_0
  - prompt-toolkit=3.0.36=py310hecd8cb5_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py310hca72f7f_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310hecd8cb5_1
  - pyopenssl=23.0.0=py310hecd8cb5_0
  - pyparsing=3.0.9=py310hecd8cb5_0
  - pyqt=5.15.7=py310he9d5cce_0
  - pyrsistent=0.18.0=py310hca72f7f_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - pytest=7.3.1=py310hecd8cb5_0
  - pytest-cov=4.0.0=py310hecd8cb5_0
  - python=3.10.11=h218abb5_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310hecd8cb5_0
  - pytorch=2.0.1=py3.10_0
  - pytorch-mutex=1.0=cpu
  - pytz=2022.7=py310hecd8cb5_0
  - pyyaml=6.0=py310h6c40b1e_1
  - pyzmq=25.0.2=py310hcec6c5f_0
  - qt-main=5.15.2=h51e0635_8
  - qt-webengine=5.15.9=h90a370e_4
  - qtconsole=5.4.2=py310hecd8cb5_0
  - qtpy=2.2.0=py310hecd8cb5_0
  - qtwebkit=5.212=hbfab81c_5
  - readline=8.2=hca72f7f_0
  - requests=2.29.0=py310hecd8cb5_0
  - ruamel.yaml=0.17.21=py310hca72f7f_0
  - ruamel.yaml.clib=0.2.6=py310hca72f7f_1
  - scipy=1.10.1=py310hdb2ea58_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=67.8.0=py310hecd8cb5_0
  - sip=6.6.2=py310he9d5cce_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py310hecd8cb5_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - soupsieve=2.4=py310hecd8cb5_0
  - sphinx=5.0.2=py310hecd8cb5_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py310hecd8cb5_0
  - tbb=2021.8.0=ha357a0b_0
  - terminado=0.17.1=py310hecd8cb5_0
  - tinycss2=1.2.1=py310hecd8cb5_0
  - tk=8.6.12=h5d9f67b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310hecd8cb5_0
  - tornado=6.2=py310hca72f7f_0
  - tqdm=4.65.0=py310h20db666_0
  - traitlets=5.7.1=py310hecd8cb5_0
  - typing-extensions=4.5.0=py310hecd8cb5_0
  - typing_extensions=4.5.0=py310hecd8cb5_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py310hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310hecd8cb5_1
  - websocket-client=0.58.0=py310hecd8cb5_4
  - wheel=0.38.4=py310hecd8cb5_0
  - widgetsnbextension=4.0.5=py310hecd8cb5_0
  - xarray=2022.11.0=py310hecd8cb5_0
  - xyzservices=2022.9.0=py310hecd8cb5_1
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h23ab428_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
  - pip:
    - absl-py==1.4.0
    - cachetools==5.3.1
    - google-auth==2.19.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.54.2
    - markdown==3.4.3
    - mpmath==1.2.1
    - nbsphinx==0.9.2
    - nbsphinx-link==1.3.0
    - neuralhydrology==1.7.0
    - oauthlib==3.2.2
    - parso==0.8.0
    - protobuf==4.23.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyqt5-sip==12.11.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - sphinx-rtd-theme==1.2.1
    - sphinxcontrib-jquery==4.1
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - werkzeug==2.3.4
```

**Additional context**
I have checked my git version, which is *2.37.1*. Looking forward to your reply, many thanks again!

**Comment by gauchm** [comment]
Hi, thanks for reporting this. To figure out the root cause: how exactly did you install neuralhydrology? via `pip install neuralhydrology`, or somehow differently? I somehow suspect the problem might be that the git command is running in a folder that's not a git repo. What's unclear to me is why you're the first to encounter this issue...

Could you please try running `git -C /Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/utils describe --always` in a shell terminal and report what happens? I assume it will fail, but the exact error will probably be helpful for debugging.

In the meantime, if my suspicion of the cause is correct, the following should unblock you (I think): 
- uninstall your current neuralhydrology installation
- clone this repository via `git clone git@github.com:neuralhydrology/neuralhydrology.git`
- `cd` into the neuralhydrology folder and execute `pip install -e .`

This way, the installation folder will be a proper git repo and the command should work.

**Comment by rogerzzl** [comment]
> Hi, thanks for reporting this. To figure out the root cause: how exactly did you install neuralhydrology? via `pip install neuralhydrology`, or somehow differently? I somehow suspect the problem might be that the git command is running in a folder that's not a git repo. What's unclear to me is why you're the first to encounter this issue...
> 
> Could you please try running `git -C /Users/roger/opt/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/neuralhydrology/utils describe --always` in a shell terminal and report what happens? I assume it will fail, but the exact error will probably be helpful for debugging.
> 
> In the meantime, if my suspicion of the cause is correct, the following should unblock you (I think):
> 
> * uninstall your current neuralhydrology installation
> * clone this repository via `git clone git@github.com:neuralhydrology/neuralhydrology.git`
> * `cd` into the neuralhydrology folder and execute `pip install -e .`
> 
> This way, the installation folder will be a proper git repo and the command should work.

Thank you, Martin! your suspicion is correct, I actually installed neuralhydrology via *pip install *.
I fixed it after following your instructions. Everything is currently normal and I'm looking forward to further exploration through neuralhydrology!

Best wished,
Roger
