### ISSUE TITLE
Trouble with "nh-results-ensemble"

### ISSUE THREAD

**Issue by julemai** [neuralhydrology/neuralhydrology#133]
Hi there,

I am trying to run the following:
```
nh-results-ensemble --run-dirs runs/seed_1 runs/seed_2 --output-dir final-training/
```

It unfortunately leads to the following error message:
```
Traceback (most recent call last):
  File "/scratch/julemai/basin-fabric/env-cuda/bin/nh-results-ensemble", line 8, in <module>
    sys.exit(_main())
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/neuralhydrology/utils/nh_results_ensemble.py", line 220, in _main
    ensemble_results = create_results_ensemble([Path(f) for f in args['run_dirs']],
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/neuralhydrology/utils/nh_results_ensemble.py", line 74, in create_results_ensemble
    return _create_ensemble(best_runs, frequencies, config)
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/neuralhydrology/utils/nh_results_ensemble.py", line 118, in _create_ensemble
    ensemble_xr['datetime'] = freq_date_range
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/xarray/core/dataset.py", line 1537, in __setitem__
    self.update({key: value})
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/xarray/core/dataset.py", line 5253, in update
    merge_result = dataset_update_method(self, other)
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/xarray/core/merge.py", line 1104, in dataset_update_method
    return merge_core(
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/xarray/core/merge.py", line 757, in merge_core
    variables, out_indexes = merge_collected(
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/xarray/core/merge.py", line 243, in merge_collected
    _assert_prioritized_valid(grouped, prioritized)
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/xarray/core/merge.py", line 190, in _assert_prioritized_valid
    raise ValueError(
ValueError: cannot set or update variable(s) 'datetime', which would corrupt the following index built from coordinates 'datetime', 'date', 'time_step':
PandasIndex(MultiIndex([('2000-01-01', 0),
            ('2000-01-02', 0),
            ('2000-01-03', 0),
           ...
            ('2010-12-31', 0)],
           name='datetime', length=4018))
```

It seems that:
```
freq_date_range =  DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08',
               '2000-01-09', '2000-01-10',
               ...
               '2010-12-22', '2010-12-23', '2010-12-24', '2010-12-25',
               '2010-12-26', '2010-12-27', '2010-12-28', '2010-12-29',
               '2010-12-30', '2010-12-31'],
              dtype='datetime64[ns]', length=4018, freq='D')
```

But `ensemble_xr ` expects a `(datetime) object MultiIndex` like:
```
ensemble_xr['datetime'] = ensemble_xr['datetime'] =  <xarray.DataArray 'datetime' (datetime: 4018)>
array([(Timestamp('2000-01-01 00:00:00'), 0),
       (Timestamp('2000-01-02 00:00:00'), 0),
       (Timestamp('2000-01-03 00:00:00'), 0), ...,
       (Timestamp('2010-12-29 00:00:00'), 0),
       (Timestamp('2010-12-30 00:00:00'), 0),
       (Timestamp('2010-12-31 00:00:00'), 0)], dtype=object)
```

If I skip this step (commenting line 118 in `nh_results_ensemble.py`), the next error message is:
```
Traceback (most recent call last):
  File "/scratch/julemai/basin-fabric/env-cuda/bin/nh-results-ensemble", line 8, in <module>
    sys.exit(_main())
  File "/scratch/julemai/basin-fabric/env-cuda/lib/python3.10/site-packages/neuralhydrology/utils/nh_results_ensemble.py", line 232, in _main
    except RuntimeError as err:
AttributeError: type object 'BaseTester' has no attribute 'metrics_to_dataframe'. Did you mean: '_metrics_to_dataframe'?
```

I am wondering if I am doing something entirely wrong... I'm happy to share the setup if that would be helpful.

Thanks, 
Julie

**Comment by gauchm** [comment]
Hi @julemai,
Thanks for pointing out these issues! We haven't used the ensembling code in a while, so it's well possible that some bugs have crept in over time.

I think there are two things going on:
1) the issue with assigning the new index. Here, I have some hope that this might just be an old xarray version. I think there were some recent-ish changes to how they handle indices. Could you check your xarray version via `conda env export`? Also, are the runs that you are trying to ensemble created by you (i.e., created with the same neuralhydrology version as you are using for ensembling now)?
2) the issue with `metrics_to_dataframe`. Apparently we messed this up in a refactoring [here](https://github.com/neuralhydrology/neuralhydrology/commit/c6fab7569f20947c710838c1da85e2a3e745dcf9#diff-13c73d4d8755665685fa2b527549c2a42f330d29871a26a8dff7be62b973ee02L382). We'll make sure to fix this with the next release.

**Comment by julemai** [comment]
Hi @gauchm,

thanks for the quick reply.

I am using pip; not conda. I hope that's not an issue. The xarray version is `xarray==2023.7.0`.

I did create the runs by myself using the same environment etc. I basically did:
```
nh-run train --config-file final-training/seed1.yml
nh-run train --config-file final-training/seed1.yml
nh-run evaluate --run-dir runs/seed1
nh-run evaluate --run-dir runs/seed2
```
and thought I would merge them now with:
```
nh-results-ensemble --run-dirs runs/seed_1 runs/seed_2 --output-dir final-training/
```

How else would I best create the ensemble mean? Or would I just always use the two (or more members) individually?

**Comment by julemai** [comment]
No trouble at all. 

The suggested revision of line 116 works.

Trying to get the `metrics_to_dataframe()` working... In the worst case I will just skip this for now.

Many thanks for your help!
