### ISSUE TITLE
[BUG] Documentation/code mismatch

### ISSUE THREAD

**Issue by amywinder900** [neuralhydrology/neuralhydrology#165]
**Describe the bug**
There is a mismatch between config argument validation and the arguments required to use the model for the stacked_forecast_lstm. 

neuralhydrology/utils/config.py line 232 raises an error when cfg['forecast_seq_length'] >= cfg['seq_length'] however according to the doc string for stacked_forecast_lstm " For example, if we want to use a hindcast sequence  length of 365 days to make a 7-day forecast, then ``seq_length`` and   ``forecast_seq_length`` must both be set to 365, and ``forecast_overlap`` must be set to 358 (=365-7)."

**To Reproduce**

Using my own data, I trained a model with 

model: stacked_forecast_lstm
seq_length: 365 
forecast_seq_length: 365
forecast_overlap: 358  

**Expected behavior**
Code should run with config arguments specified in documentation. 

**Description of the dataset**
Used a river flow dataset. It has worked using other model configurations. 

**Logs & Screenshots**
Traceback (most recent call last):
  File "c:\Users\amywinder\Documents\ML%20for%20Forecasting\working_folder\basic_model_testing\train_model.py", line 20, in <module>
    start_run(config_file=Path(relative_path))
  File "C:\Anaconda3\envs\neuralhydrology\lib\site-packages\neuralhydrology\nh_run.py", line 68, in start_run
    config = Config(config_file)
  File "C:\Anaconda3\envs\neuralhydrology\lib\site-packages\neuralhydrology\utils\config.py", line 45, in __init__
    self._cfg = Config._read_and_parse_config(yml_path=yml_path_or_dict)
  File "C:\Anaconda3\envs\neuralhydrology\lib\site-packages\neuralhydrology\utils\config.py", line 258, in _read_and_parse_config
    cfg = Config._parse_config(cfg)
  File "C:\Anaconda3\envs\neuralhydrology\lib\site-packages\neuralhydrology\utils\config.py", line 233, in _parse_config
    raise ValueError('Forecast sequence length must be < sequence length.')
ValueError: Forecast sequence length must be < sequence length.

**Desktop & Environment (please complete the following information):**
 - OS: Windows
 - version number "1.9.1"
 - The Python version and a list of installed Python packages. 
 - name: neuralhydrology
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anyio=3.5.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py310haa95532_0
  - attrs=23.1.0=py310haa95532_0
  - babel=2.11.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=3.3.0=py310h9909e9c_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py310hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - certifi=2023.11.17=py310haa95532_0
  - cffi=1.16.0=py310h2bbff1b_0
  - cftime=1.6.2=py310h9128911_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - contourpy=1.2.0=py310h59b6b97_0
  - coverage=7.2.2=py310h2bbff1b_0
  - cryptography=41.0.7=py310h89fc84f_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.18.1=py310haa95532_3
  - exceptiongroup=1.0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py310haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - gmpy2=2.1.2=py310h7f96b67_0
  - h5py=3.9.0=py310hfc34f40_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.4=py310haa95532_0
  - imagesize=1.4.1=py310haa95532_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.25.0=py310h9909e9c_0
  - ipython=8.15.0=py310haa95532_0
  - ipywidgets=8.0.4=py310haa95532_0
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter=1.0.0=py310haa95532_8
  - jupyter-lsp=2.2.0=py310haa95532_0
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - jupyter_core=5.5.0=py310haa95532_0
  - jupyter_events=0.8.0=py310haa95532_0
  - jupyter_server=2.10.0=py310haa95532_0
  - jupyter_server_terminals=0.4.4=py310haa95532_1
  - jupyterlab=4.0.8=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py310haa95532_0
  - jupyterlab_widgets=3.0.9=py310haa95532_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcurl=8.4.0=h86230a5_1
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libnetcdf=4.8.1=h6685c40_4
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=he2ea4bf_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libzip=1.8.0=h289538f_1
  - llvmlite=0.41.0=py310hf2fb9eb_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.8.0=py310haa95532_0
  - matplotlib-base=3.8.0=py310h4ed8f06_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mistune=2.0.4=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - munkres=1.1.4=py_0
  - nbclient=0.8.0=py310haa95532_0
  - nbconvert=7.10.0=py310haa95532_0
  - nbformat=5.9.2=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - netcdf4=1.6.2=py310hadf358c_0
  - networkx=3.1=py310haa95532_0
  - notebook=7.0.6=py310haa95532_0
  - notebook-shim=0.2.3=py310haa95532_0
  - numba=0.58.1=py310hd77b12b_0
  - numexpr=2.8.7=py310h2cd9be0_0
  - numpy=1.26.2=py310h055cbcc_0
  - numpy-base=1.26.2=py310h65a83cf_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.12=h2bbff1b_0
  - overrides=7.4.0=py310haa95532_0
  - packaging=23.1=py310haa95532_0
  - pandas=2.1.4=py310h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py310h045eedc_0
  - pip=23.3.1=py310haa95532_0
  - platformdirs=3.10.0=py310haa95532_0
  - pluggy=1.0.0=py310haa95532_1
  - ply=3.11=py310haa95532_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310haa95532_1
  - pyopenssl=23.2.0=py310haa95532_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.10=py310hd77b12b_0
  - pyqt5-sip=12.13.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - pytest=7.4.0=py310haa95532_0
  - pytest-cov=4.1.0=py310haa95532_1
  - python=3.10.13=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-json-logger=2.0.7=py310haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.1.2=py3.10_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pywinpty=2.0.10=py310h5da7b33_0
  - pyyaml=6.0.1=py310h2bbff1b_0
  - pyzmq=25.1.0=py310hd77b12b_0
  - qt-main=5.15.2=h19c9488_10
  - qtconsole=5.5.0=py310haa95532_0
  - qtpy=2.4.1=py310haa95532_0
  - referencing=0.30.2=py310haa95532_0
  - requests=2.31.0=py310haa95532_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.10.6=py310h062c2fa_0
  - ruamel.yaml=0.17.21=py310h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py310h2bbff1b_1
  - scipy=1.11.4=py310h309d312_0
  - send2trash=1.8.2=py310haa95532_0
  - setuptools=68.2.2=py310haa95532_0
  - sip=6.7.12=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py310haa95532_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - soupsieve=2.5=py310haa95532_0
  - sphinx=5.0.2=py310haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py310haa95532_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - tornado=6.3.3=py310h2bbff1b_0
  - tqdm=4.65.0=py310h9909e9c_0
  - traitlets=5.7.1=py310haa95532_0
  - typing-extensions=4.7.1=py310haa95532_0
  - typing_extensions=4.7.1=py310haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - wheel=0.41.2=py310haa95532_0
  - widgetsnbextension=4.0.5=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winpty=0.4.3=4
  - xarray=2023.6.0=py310haa95532_0
  - xyzservices=2022.9.0=py310haa95532_1
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.0.0
      - cachetools==5.3.2
      - fsspec==2023.12.2
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - markdown==3.5.1
      - nbsphinx==0.9.3
      - nbsphinx-link==1.3.0
      - neuralhydrology==1.9.1
      - oauthlib==3.2.2
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-jquery==4.1
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - werkzeug==3.0.1

**Additional context**
I'm not really sure what the correct configuration arguments should be so it may be a documentation issue or it may be an actual bug.

**Comment by kratzert** [comment]
Hi @amywinder900 

sorry for the late reply. I hope you could resolve this issue in the meantime yourself. If not: Yes you are right, the docstring in stacked-forecast-lstm is wrong. forecast_seq_length has to be shorter than the total sequence length. E.g. you want to make a 7 day forecast, and have a 1 year lookback, than seq_length = 372 ( = 365 + 7) and forecast_seq_length=7. If you want to let the hindcast and forecast model run in parallel for a few timesteps, you can define this with the overlap argument.

I will update the docstring in one of the upcoming version upgrades.

**Comment by pedrozamboni** [comment]
Hi, I tried to set my parameter as described on the comment above, but I got an ValueError.
 
ValueError: Hindcast and forecast sequences must be equal.

My config:

forecast_overlap: 5
seq_length: 372
forecast_seq_length: 7
bidirectional_stacked_forecast_lstm: true

**Comment by grey-nearing** [comment]
Hi [amywinder900](https://github.com/amywinder900) & [pedrozamboni](https://github.com/pedrozamboni),

Thank you for raising this issue. There is an error in the doc string for the Stacked Forecast LSTM. The correct way to assign the sequence length parameters is as follows:

1) The `seq_length` parameter is the total sequence length, inclusive of hindcast and forecast.
2) The `forecast_seq_length` is the length of the input sequence that goes into the forecast portion of the Stacked Forecast LSTM.
3) The `forecast_seq_overlap` is the number of timesteps where the hindcast and forecast portions of the Stacked Forecast LSTM overlap.

As an example, suppose you wanted to use 365 days of spin-up to make a 7-day forecast, you would use the following sequence length parameters:

seq_length: 372
forecast_overlap: 358
forecast_seq_length: 365

**Comment by gauchm** [comment]
I think this is resolved with [v1.12.0](https://github.com/neuralhydrology/neuralhydrology/releases/tag/v1.12.0), so I'm closing the issue. I'm not sure what you mean by "pipeline for inference or application", @pedrozamboni. You can use the normal `nh_run evaluate` CLI or `eval_run` API commands/functions as described in https://neuralhydrology.readthedocs.io/en/latest/tutorials/introduction.html for inference.
