### ISSUE TITLE
[BUG] Problem  for handoff_forecast_lstm

### ISSUE THREAD

**Issue by Smile-L-up** [neuralhydrology/neuralhydrology#174]
I configured the handoff_forecast_lstm model according to [finetuning config](https://github.com/neuralhydrology/neuralhydrology/blob/master/examples/06-Finetuning/531_basins.yml),  But the following error occurred：
```python
Traceback (most recent call last):
  File "D:\Smile_L\pycharm_files\neuralhydrology\examples\06-Finetuning\finetuning.py", line 13, in <module>
    start_run(config_file=Path("531_basins.yml"))
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\nh_run.py", line 76, in start_run
    start_training(config)
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\training\train.py", line 20, in start_training
    trainer.train_and_validate()
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\training\basetrainer.py", line 214, in train_and_validate
    self._train_epoch(epoch=epoch)
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\training\basetrainer.py", line 296, in _train_epoch
    predictions = self.model(data)
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\modelzoo\handoff_forecast_lstm.py", line 122, in forward
    x_h = self.hindcast_embedding_net(data)
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\modelzoo\inputlayer.py", line 152, in forward
    x_d = data[data_type].transpose(0, 1)
KeyError: 'x_h'
```
If I modify the following code in the handoff_forecast_lstm.py , it can run
```python
        self.forecast_embedding_net = InputLayer(cfg, embedding_type='forecast')
        self.hindcast_embedding_net = InputLayer(cfg, embedding_type='hindcast')

        self.forecast_embedding_net = InputLayer(cfg, embedding_type='full_model')
        self.hindcast_embedding_net = InputLayer(cfg, embedding_type='full_model')
```
The specific reason is because there is only the index of x_d in the data
```python
        if self.embedding_type == 'full_model':
            data_type = 'x_d'
        elif self.embedding_type == 'forecast':
            data_type = 'x_f'
        elif self.embedding_type == 'hindcast':
            data_type = 'x_h'
        x_d = data[data_type].transpose(0, 1)
```

 the specific configuration.
```python
# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: cudalstm_531_basins

# place to store run directory (if empty runs are stored in $cwd$/runs/)
run_dir:

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: 531_basin_list.txt
validation_basin_file: 531_basin_list.txt
test_basin_file: 531_basin_list.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: '01/10/1999'
train_end_date: '30/09/2008'
validation_start_date: '01/10/1980'
validation_end_date: '30/09/1989'
test_start_date: '01/10/1989'
test_end_date: '30/09/1999'

# fixed seed, leave empty to use a random seed
seed: 123

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 1

# specify how many random basins to use for validation
validate_n_random_basins: 531

# specify which metrics to calculate during validation (see codebase.evaluation.metrics)
metrics:
- NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, shortcutlstm, dropoutlstm, cudalstminitialh, handoff_forecast_lstm ]
# (has to match the if statement in modelzoo/__init__.py)
model: handoff_forecast_lstm


#An integer number of timesteps where forecast data overlaps with hindcast data. This does not add to the forecast_sequence_length, and must be no larger than the forecast_sequence_length
forecast_overlap: 2
forecast_seq_length: 184
state_handoff_network: {"type": "full_model", "hiddens": 128}

# prediction head [regression, mdn, umal]. Define the head specific parameters below
head: regression

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 128

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

output_activation: linear

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam, Adadelta]
optimizer: Adam

# specify loss [MSE, NSE, RMSE, UMALLoss, MDNLoss]
loss: NSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 1e-3
    1: 5e-4

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 3

# If True, clips norm of gradients
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length
predict_last_n: 1

# Length of the input sequence
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 8

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# Save model weights every n epochs
save_weights_every: 1

# Store the results of the validation to disk
save_validation_results: True

# --- Data configurations --------------------------------------------------------------------------

dataset: camels_us

# Path to CAMELS data set
data_dir: ../../data/CAMELS_US

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended]
# can be either a list of forcings or a single forcing product
forcings:
- daymet

# variables to use as time series input (names match the data file column headers)
# Note: In case of multiple input forcing products, you have to append the forcing product behind
# each variable. E.g. 'prcp(mm/day)' of the daymet product is 'prcp(mm/day)_daymet'
dynamic_inputs:
- prcp(mm/day)
- srad(W/m2)
- tmax(C)
- tmin(C)
- vp(Pa)

# which columns to use as target
target_variables:
- QObs(mm/d)

static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
```

The specific parameters that are different from [finetuning config](https://github.com/neuralhydrology/neuralhydrology/blob/master/examples/06-Finetuning/531_basins.yml) are as follows:
```python
# (has to match the if statement in modelzoo/__init__.py)
model: handoff_forecast_lstm


#An integer number of timesteps where forecast data overlaps with hindcast data. This does not add to the forecast_sequence_length, and must be no larger than the forecast_sequence_length
forecast_overlap: 2
forecast_seq_length: 184
state_handoff_network: {"type": "full_model", "hiddens": 128}
```
In addition, can you give some suggestions on how to set these parameters?
Any help will be great. Thanks!

**Comment by Smile-L-up** [comment]
Great,! For daily modeling, I use [finetuning config](https://github.com/neuralhydrology/neuralhydrology/blob/master/examples/06-Finetuning/531_basins.yml) configuration and this can run，but the effect is not as good as cudaLSTM. I don’t know if there is any problem with my configuration. What's worse，ome issues arise when I try to run through the hourly data. For hourly modeling, i use the multi timescale config.  There is a problem for dynamic inputs.
error info
```python 
KeyError: "The following features are not available in the data: ['convective_fraction_nldas_hourly', 'longwave_radiation_nldas_hourly', 'potential_energy_nldas_hourly', 'potential_evaporation_nldas_hourly', 'pressure_nldas_hourly', 'shortwave_radiation_nldas_hourly', 'specific_humidity_nldas_hourly', 'temperature_nldas_hourly', 'total_precipitation_nldas_hourly', 'wind_u_nldas_hourly', 'wind_v_nldas_hourly']. These are the available features: ['convective_fraction', 'longwave_radiation', 'potential_energy', 'potential_evaporation', 'pressure', 'shortwave_radiation', 'specific_humidity', 'temperature', 'total_precipitation', 'wind_u', 'wind_v', 'qobs_mm_per_hour', 'qobs_count', 'qualifiers', 'utcoffset_hours', 'rel_deviation_from_camels', 'qobs_CAMELS_mm_per_hour', 'basin']"
```


config for daymat (finetuning config)
```python
# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: cudalstm_531_basins

# place to store run directory (if empty runs are stored in $cwd$/runs/)
run_dir:

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: 531_basin_list.txt
validation_basin_file: 531_basin_list.txt
test_basin_file: 531_basin_list.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: '01/10/1999'
train_end_date: '30/09/2008'
validation_start_date: '01/10/1980'
validation_end_date: '30/09/1989'
test_start_date: '01/10/1989'
test_end_date: '30/09/1999'

# fixed seed, leave empty to use a random seed
seed: 123

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 1

# specify how many random basins to use for validation
validate_n_random_basins: 531

# specify which metrics to calculate during validation (see codebase.evaluation.metrics)
metrics:
- NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, shortcutlstm, dropoutlstm, cudalstminitialh, handoff_forecast_lstm ]
# (has to match the if statement in modelzoo/__init__.py)
model: handoff_forecast_lstm


#An integer number of timesteps where forecast data overlaps with hindcast data. This does not add to the forecast_sequence_length, and must be no larger than the forecast_sequence_length
forecast_overlap: 2
forecast_seq_length: 184
state_handoff_network: {"type": "full_model", "hiddens": 128}
forecast_inputs:
- prcp(mm/day)
- srad(W/m2)
- tmax(C)
- tmin(C)
- vp(Pa)
hindcast_inputs:
- prcp(mm/day)
- srad(W/m2)
- tmax(C)
- tmin(C)
- vp(Pa)

# prediction head [regression, mdn, umal]. Define the head specific parameters below
head: regression

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 128

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

output_activation: linear

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam, Adadelta]
optimizer: Adam

# specify loss [MSE, NSE, RMSE, UMALLoss, MDNLoss]
loss: NSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 1e-3
    1: 5e-4

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 3

# If True, clips norm of gradients
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length
predict_last_n: 1

# Length of the input sequence
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 8

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# Save model weights every n epochs
save_weights_every: 1

# Store the results of the validation to disk
save_validation_results: True

# --- Data configurations --------------------------------------------------------------------------

dataset: camels_us

# Path to CAMELS data set
data_dir: ../../data/CAMELS_US

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended]
# can be either a list of forcings or a single forcing product
forcings:
- daymet

# variables to use as time series input (names match the data file column headers)
# Note: In case of multiple input forcing products, you have to append the forcing product behind
# each variable. E.g. 'prcp(mm/day)' of the daymet product is 'prcp(mm/day)_daymet'
dynamic_inputs:
- prcp(mm/day)
- srad(W/m2)
- tmax(C)
- tmin(C)
- vp(Pa)

# which columns to use as target
target_variables:
- QObs(mm/d)

static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
```
config for hourly ( multi timescale config)
```python
# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: test_run

# input and output frequencies
use_frequencies:
  - 1H
#  - 1D

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: 1_basin.txt
validation_basin_file: 1_basin.txt
test_basin_file: 1_basin.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: "01/10/1999"
train_end_date: "30/09/2008"
validation_start_date: "01/10/1996"
validation_end_date: "30/09/1999"
test_start_date: "01/10/1989"
test_end_date: "30/09/1996"

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 5

# specify how many random basins to use for validation
validate_n_random_basins: 1

# specify which metrics to calculate during validation (see neuralhydrology.evaluation.metrics)
# this can either be a list or a dictionary. If a dictionary is used, the inner keys must match the name of the
# target_variable specified below. Using dicts allows for different metrics per target variable.
metrics:
  - NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, mtslstm]
# (has to match the if statement in modelzoo/__init__.py)
model: handoff_forecast_lstm

# select whether to use the MTS-LSTM or sMTS-LSTM
shared_mtslstm: False

# define whether the MTS-LSTM's state transfer layer uses an
# identity or linear operation for hidden (h) and cell state (c).
transfer_mtslstm_states:
  h: linear
  c: linear

# prediction head [regression]. Define the head specific parameters below
head: regression

# ----> Regression settings <----
output_activation: linear

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 20

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam]
optimizer: Adam

# specify loss [MSE, NSE, RMSE]
loss: MSE

# specify regularization
regularization:
  - tie_frequencies

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
  0: 1e-2
  30: 5e-3
  40: 1e-3

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 50

# If a value, clips the gradients during training to that norm.
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length.
# If use_frequencies is used, this needs to be a dict mapping each frequency to a predict_last_n-value, else an int.
predict_last_n:
#  1D: 1
  1H: 24

# Length of the input sequence
# If use_frequencies is used, this needs to be a dict mapping each frequency to a seq_length, else an int.
seq_length:
#  1D: 365
  1H: 336

# Number of parallel workers used in the data pipeline
num_workers: 0

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: False

# If a value and greater than 0, logs n random basins as figures during validation
log_n_figures: 0

# Save model weights every n epochs
save_weights_every: 1

# --- Data configurations --------------------------------------------------------------------------

# which data set to use [camels_us, camels_gb, global, hourly_camels_us]
dataset: hourly_camels_us

# Path to data set root
data_dir: ../../data/CAMELS_US

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, nldas_hourly]
# can be either a list of forcings or a single forcing product
forcings:
  - nldas_hourly
#  - daymet

dynamic_inputs:
#  1D:
#    - prcp(mm/day)_daymet
#    - srad(W/m2)_daymet
#    - tmax(C)_daymet
#    - tmin(C)_daymet
#    - vp(Pa)_daymet
  1H:
    - convective_fraction_nldas_hourly
    - longwave_radiation_nldas_hourly
    - potential_energy_nldas_hourly
    - potential_evaporation_nldas_hourly
    - pressure_nldas_hourly
    - shortwave_radiation_nldas_hourly
    - specific_humidity_nldas_hourly
    - temperature_nldas_hourly
    - total_precipitation_nldas_hourly
    - wind_u_nldas_hourly
    - wind_v_nldas_hourly


# which columns to use as target
target_variables:
  - qobs_mm_per_hour

# clip negative predictions to zero for all variables listed below. Should be a list, even for single variables.
clip_targets_to_zero:
  - qobs_mm_per_hour

```
Looking forward to your reply
