### ISSUE TITLE
An attempt has been made to start a new process before the current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by rhedouin** [neuralhydrology/neuralhydrology#190]
Hi, 

I just started to try this toolbox following the Introduction tutorial with the camels_us dataset. 
When I launch the training from a terminal it works perfectly fine i.e.
nh-run train --config-file .\1_basin.yml

Yet, when I tried to execute the mini-script (below) proposed in the tutorial (which I will need at some point to train on my own database), it crashed (reported below). If anyone could help me here, it would be appreciated!

Cheers

########################## Code
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import torch
from neuralhydrology.evaluation import metrics
from neuralhydrology.nh_run import start_run, eval_run

start_run(config_file=Path("1_basin.yml"), **gpu=-1)**

########################### Output
2024-06-19 18:00:21,085: Logging to C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180020\output.log initialized.
2024-06-19 18:00:21,087: ### Folder structure created at C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180020
2024-06-19 18:00:21,089: ### Run configurations for test_run
2024-06-19 18:00:21,090: experiment_name: test_run
2024-06-19 18:00:21,091: train_basin_file: 1_basin.txt
2024-06-19 18:00:21,092: validation_basin_file: 1_basin.txt
2024-06-19 18:00:21,093: test_basin_file: 1_basin.txt
2024-06-19 18:00:21,096: train_start_date: 1999-10-01 00:00:00
2024-06-19 18:00:21,098: train_end_date: 2008-09-30 00:00:00
2024-06-19 18:00:21,100: validation_start_date: 1980-10-01 00:00:00
2024-06-19 18:00:21,101: validation_end_date: 1989-09-30 00:00:00
2024-06-19 18:00:21,101: test_start_date: 1989-10-01 00:00:00
2024-06-19 18:00:21,102: test_end_date: 1999-09-30 00:00:00
2024-06-19 18:00:21,103: device: cpu
2024-06-19 18:00:21,104: validate_every: 3
2024-06-19 18:00:21,104: validate_n_random_basins: 1
2024-06-19 18:00:21,105: metrics: ['NSE']
2024-06-19 18:00:21,106: model: cudalstm
2024-06-19 18:00:21,107: head: regression
2024-06-19 18:00:21,109: output_activation: linear
2024-06-19 18:00:21,112: hidden_size: 20
2024-06-19 18:00:21,114: initial_forget_bias: 3
2024-06-19 18:00:21,116: output_dropout: 0.4
2024-06-19 18:00:21,117: optimizer: Adam
2024-06-19 18:00:21,119: loss: MSE
2024-06-19 18:00:21,120: learning_rate: {0: 0.01, 30: 0.005, 40: 0.001}
2024-06-19 18:00:21,121: batch_size: 256
2024-06-19 18:00:21,122: epochs: 50
2024-06-19 18:00:21,123: clip_gradient_norm: 1
2024-06-19 18:00:21,126: predict_last_n: 1
2024-06-19 18:00:21,127: seq_length: 365
2024-06-19 18:00:21,129: num_workers: 8
2024-06-19 18:00:21,135: log_interval: 5
2024-06-19 18:00:21,136: log_tensorboard: True
2024-06-19 18:00:21,137: log_n_figures: 1
2024-06-19 18:00:21,138: save_weights_every: 1
2024-06-19 18:00:21,139: dataset: camels_us
2024-06-19 18:00:21,140: data_dir: D:\Flood\CAMELS_US
2024-06-19 18:00:21,140: forcings: ['maurer', 'daymet', 'nldas']
2024-06-19 18:00:21,140: dynamic_inputs: ['PRCP(mm/day)_nldas', 'PRCP(mm/day)_maurer', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet'] 
2024-06-19 18:00:21,141: target_variables: ['QObs(mm/d)']
2024-06-19 18:00:21,142: clip_targets_to_zero: ['QObs(mm/d)']
2024-06-19 18:00:21,143: number_of_basins: 1
2024-06-19 18:00:21,144: run_dir: C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180020
2024-06-19 18:00:21,145: train_dir: C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180020\train_data
2024-06-19 18:00:21,146: img_log_dir: C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180020\img_log
2024-06-19 18:00:21,166: ### Device cpu will be used for training
2024-06-19 18:00:21,169: Loading basin data into xarray data set.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:25<00:00, 25.51s/it]
2024-06-19 18:00:46,751: Create lookup table and convert to pytorch tensor
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.66s/it]
# Epoch 1:   0%|                                                                                                                                                | 0/13 [00:00<?, ?it/s]Hello world!
2024-06-19 18:01:23,255: Logging to C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180123\output.log initialized.
2024-06-19 18:01:23,255: ### Folder structure created at C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180123
2024-06-19 18:01:23,259: ### Run configurations for test_run
2024-06-19 18:01:23,259: experiment_name: test_run
2024-06-19 18:01:23,263: train_basin_file: 1_basin.txt
2024-06-19 18:01:23,263: validation_basin_file: 1_basin.txt
2024-06-19 18:01:23,267: test_basin_file: 1_basin.txt
2024-06-19 18:01:23,275: train_start_date: 1999-10-01 00:00:00
2024-06-19 18:01:23,279: train_end_date: 2008-09-30 00:00:00
2024-06-19 18:01:23,287: validation_start_date: 1980-10-01 00:00:00
2024-06-19 18:01:23,287: validation_end_date: 1989-09-30 00:00:00
2024-06-19 18:01:23,287: test_start_date: 1989-10-01 00:00:00
2024-06-19 18:01:23,291: test_end_date: 1999-09-30 00:00:00
2024-06-19 18:01:23,291: device: cpu
2024-06-19 18:01:23,291: validate_every: 3
2024-06-19 18:01:23,291: validate_n_random_basins: 1
2024-06-19 18:01:23,291: metrics: ['NSE']
2024-06-19 18:01:23,295: model: cudalstm
2024-06-19 18:01:23,295: head: regression
2024-06-19 18:01:23,295: output_activation: linear
2024-06-19 18:01:23,295: hidden_size: 20
2024-06-19 18:01:23,299: initial_forget_bias: 3
2024-06-19 18:01:23,299: output_dropout: 0.4
2024-06-19 18:01:23,299: optimizer: Adam
2024-06-19 18:01:23,303: loss: MSE
2024-06-19 18:01:23,307: learning_rate: {0: 0.01, 30: 0.005, 40: 0.001}
2024-06-19 18:01:23,307: batch_size: 256
2024-06-19 18:01:23,311: epochs: 50
2024-06-19 18:01:23,311: clip_gradient_norm: 1
2024-06-19 18:01:23,311: predict_last_n: 1
2024-06-19 18:01:23,311: seq_length: 365
2024-06-19 18:01:23,315: num_workers: 8
2024-06-19 18:01:23,315: log_interval: 5
2024-06-19 18:01:23,315: log_tensorboard: True
2024-06-19 18:01:23,319: log_n_figures: 1
2024-06-19 18:01:23,319: save_weights_every: 1
2024-06-19 18:01:23,323: dataset: camels_us
2024-06-19 18:01:23,323: data_dir: D:\Flood\CAMELS_US
2024-06-19 18:01:23,323: forcings: ['maurer', 'daymet', 'nldas']
2024-06-19 18:01:23,323: dynamic_inputs: ['PRCP(mm/day)_nldas', 'PRCP(mm/day)_maurer', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']
2024-06-19 18:01:23,327: target_variables: ['QObs(mm/d)']
2024-06-19 18:01:23,327: clip_targets_to_zero: ['QObs(mm/d)']
2024-06-19 18:01:23,327: number_of_basins: 1
2024-06-19 18:01:23,331: run_dir: C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180123
2024-06-19 18:01:23,331: train_dir: C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180123\train_data
2024-06-19 18:01:23,331: img_log_dir: C:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\runs\test_run_1906_180123\img_log
2024-06-19 18:01:23,351: ### Device cpu will be used for training
2024-06-19 18:01:23,355: Loading basin data into xarray data set.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it] 
2024-06-19 18:01:26,396: Create lookup table and convert to pytorch tensor
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.25s/it]
# Epoch 1:   0%|                                                                                                                                                | 0/13 [00:00<?, ?it/s]
2024-06-19 18:01:37,167: Uncaught exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\renau\Documents\Code\Python\neuralhydrology\examples\01-Introduction\first_test.py", line 11, in <module>
    start_run(config_file=Path("1_basin.yml"), gpu=-1)
  File "c:\users\renau\documents\code\python\neuralhydrology\neuralhydrology\nh_run.py", line 76, in start_run
    start_training(config)
  File "c:\users\renau\documents\code\python\neuralhydrology\neuralhydrology\training\train.py", line 20, in start_training
    trainer.train_and_validate()
  File "c:\users\renau\documents\code\python\neuralhydrology\neuralhydrology\training\basetrainer.py", line 214, in train_and_validate
    self._train_epoch(epoch=epoch)
  File "c:\users\renau\documents\code\python\neuralhydrology\neuralhydrology\training\basetrainer.py", line 284, in _train_epoch
    for i, data in enumerate(pbar):
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\renau\Documents\Code\Python\neuralhydrology\.conda\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

**Comment by gauchm** [comment]
As suggested by the link at the very end of the error message, what should solve this is wrapping the start_run call in an 
```py
if __name__ == '__main__':
  start_run(config_file=Path("1_basin.yml"), gpu=-1)
```

This is a general best practice pattern in any Python script. It ensures that any process spawned within the script (e.g., for dataloading) doesn't start executing all the code again.

**Comment by rhedouin** [comment]
Indeed it works, thank you very much
