### ISSUE TITLE
Trouble running MTS notebook

### ISSUE THREAD

**Issue by chuckaustin** [neuralhydrology/neuralhydrology#75]
[Part of JOSS Review: https://github.com/https://github.com/openjournals/joss-reviews/issues/4050]

I've been going through the examples, and so far haven't run into much trouble. However, I'm getting stuck on Example 4 ("Multi-Timescale Prediction"). When I try to train the model using either nh-run or the python API, the process aborts right before the first epoch. 

Copying output below. Have I missed something? 

```
(neuralhydrology) C:\Users\321319\Documents\neuralhydrology\examples\04-Multi-Timescale>nh-run train --config-file 1_basin.yml
2022-02-17 17:27:05,401: Logging to C:\Users\321319\Documents\neuralhydrology\examples\04-Multi-Timescale\runs\test_run_1702_172705\output.log initialized.
2022-02-17 17:27:05,401: ### Folder structure created at C:\Users\321319\Documents\neuralhydrology\examples\04-Multi-Timescale\runs\test_run_1702_172705
2022-02-17 17:27:05,412: ### Run configurations for test_run
2022-02-17 17:27:05,432: experiment_name: test_run
2022-02-17 17:27:05,465: use_frequencies: ['1H', '1D']
2022-02-17 17:27:05,501: train_basin_file: 1_basin.txt
2022-02-17 17:27:05,516: validation_basin_file: 1_basin.txt
2022-02-17 17:27:05,548: test_basin_file: 1_basin.txt
2022-02-17 17:27:05,560: train_start_date: 1999-10-01 00:00:00
2022-02-17 17:27:05,585: train_end_date: 2008-09-30 00:00:00
2022-02-17 17:27:05,618: validation_start_date: 1996-10-01 00:00:00
2022-02-17 17:27:05,653: validation_end_date: 1999-09-30 00:00:00
2022-02-17 17:27:05,696: test_start_date: 1989-10-01 00:00:00
2022-02-17 17:27:05,733: test_end_date: 1996-09-30 00:00:00
2022-02-17 17:27:05,742: device: cpu
2022-02-17 17:27:05,769: validate_every: 5
2022-02-17 17:27:05,780: validate_n_random_basins: 1
2022-02-17 17:27:05,808: metrics: ['NSE']
2022-02-17 17:27:05,820: model: mtslstm
2022-02-17 17:27:05,849: shared_mtslstm: False
2022-02-17 17:27:05,882: transfer_mtslstm_states: {'h': 'linear', 'c': 'linear'}
2022-02-17 17:27:05,882: head: regression
2022-02-17 17:27:05,901: output_activation: linear
2022-02-17 17:27:05,915: hidden_size: 20
2022-02-17 17:27:05,923: initial_forget_bias: 3
2022-02-17 17:27:05,946: output_dropout: 0.4
2022-02-17 17:27:05,980: optimizer: Adam
2022-02-17 17:27:06,013: loss: MSE
2022-02-17 17:27:06,021: regularization: ['tie_frequencies']
2022-02-17 17:27:06,046: learning_rate: {0: 0.01, 30: 0.005, 40: 0.001}
2022-02-17 17:27:06,079: batch_size: 256
2022-02-17 17:27:06,112: epochs: 50
2022-02-17 17:27:06,124: clip_gradient_norm: 1
2022-02-17 17:27:06,146: predict_last_n: {'1D': 1, '1H': 24}
2022-02-17 17:27:06,148: seq_length: {'1D': 365, '1H': 336}
2022-02-17 17:27:06,162: num_workers: 8
2022-02-17 17:27:06,180: log_interval: 5
2022-02-17 17:27:06,187: log_tensorboard: False
2022-02-17 17:27:06,213: log_n_figures: 0
2022-02-17 17:27:06,246: save_weights_every: 1
2022-02-17 17:27:06,253: dataset: hourly_camels_us
2022-02-17 17:27:06,279: data_dir: ..\..\data\CAMELS_US
2022-02-17 17:27:06,313: forcings: ['nldas_hourly', 'daymet']
2022-02-17 17:27:06,346: dynamic_inputs: {'1D': ['prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet'], '1H': ['convective_fraction_nldas_hourly', 'longwave_radiation_nldas_hourly', 'potential_energy_nldas_hourly', 'potential_evaporation_nldas_hourly', 'pressure_nldas_hourly', 'shortwave_radiation_nldas_hourly', 'specific_humidity_nldas_hourly', 'temperature_nldas_hourly', 'total_precipitation_nldas_hourly', 'wind_u_nldas_hourly', 'wind_v_nldas_hourly', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']}
2022-02-17 17:27:06,381: target_variables: ['qobs_mm_per_hour']
2022-02-17 17:27:06,413: clip_targets_to_zero: ['qobs_mm_per_hour']
2022-02-17 17:27:06,423: number_of_basins: 1
2022-02-17 17:27:06,446: run_dir: C:\Users\321319\Documents\neuralhydrology\examples\04-Multi-Timescale\runs\test_run_1702_172705
2022-02-17 17:27:06,459: train_dir: C:\Users\321319\Documents\neuralhydrology\examples\04-Multi-Timescale\runs\test_run_1702_172705\train_data
2022-02-17 17:27:06,480: img_log_dir: C:\Users\321319\Documents\neuralhydrology\examples\04-Multi-Timescale\runs\test_run_1702_172705\img_log
2022-02-17 17:27:06,518: ### Device cpu will be used for training
2022-02-17 17:27:06,525: No specific hidden size for frequencies are specified. Same hidden size is used for all.
2022-02-17 17:27:06,553: Loading basin data into xarray data set.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.46it/s]
2022-02-17 17:27:07,312: Create lookup table and convert to pytorch tensor
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
# Epoch 1:   0%|                                                                                                                                                               | 0/11 [00:00<?, ?it/s]
2022-02-17 17:27:09,078: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\Scripts\nh-run-script.py", line 33, in <module>
    sys.exit(load_entry_point('neuralhydrology', 'console_scripts', 'nh-run')())
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\nh_run.py", line 43, in _main
    start_run(config_file=Path(args["config_file"]), gpu=args["gpu"])
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\nh_run.py", line 76, in start_run
    start_training(config)
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\training\train.py", line 23, in start_training
    trainer.train_and_validate()
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\training\basetrainer.py", line 205, in train_and_validate
    self._train_epoch(epoch=epoch)
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\training\basetrainer.py", line 272, in _train_epoch
    for data in pbar:
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by chuckaustin** [comment]
Hi @gauchm, thanks for your response. I've made it through all the examples now except for the last one (which I have started, but haven't finished yet, as I'm running it on a CPU). The MTS notebook is the only place I get this particular error.

Setting num_workers to 0 made it execute! It also makes most of the other examples run faster on my machine, which I guess is because I'm running it on a single CPU. 

Here is the output from conda env export. Would be awesome if there's an easy fix to make the software run on my GPU. As I mentioned in my other post, I created the environment using environment_cuda9_2.yml

```
(neuralhydrology) C:\Users\321319\Documents\neuralhydrology\examples\06-Finetuning>conda env export
name: neuralhydrology
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - async_generator=1.10=py37h28b3542_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=2.4.2=py37haa95532_0
  - bottleneck=1.3.2=py37h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2021.10.26=haa95532_4
  - cached-property=1.5.2=py_0
  - certifi=2021.10.8=py37haa95532_2
  - cffi=1.15.0=py37h2bbff1b_1
  - cftime=1.5.1.1=py37h080aedc_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py37h2bbff1b_2
  - cryptography=36.0.0=py37h21b164f_0
  - cudatoolkit=9.2=0
  - curl=7.55.1=vc14hdaba4a4_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.17.1=py37haa95532_1
  - entrypoints=0.3=py37_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - h5py=3.6.0=py37h3de5c98_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc14hc45fdbb_0
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py37haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.4.1=py37haa95532_1
  - ipython=7.31.1=py37haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9b=vc14h4d7706e_1
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.2=py37hd77b12b_0
  - libcurl=7.80.0=h86230a5_0
  - libnetcdf=4.6.1=hf59b723_4
  - libpng=1.6.37=h2a8f88b_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.0=h2bbff1b_0
  - llvmlite=0.37.0=py37h23ce68f_1
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=2.0.1=py37h2bbff1b_0
  - matplotlib=3.5.0=py37haa95532_0
  - matplotlib-base=3.5.0=py37h6214cd6_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - netcdf4=1.5.7=py37hb33177a_0
  - notebook=6.4.8=py37haa95532_0
  - numba=0.54.1=py37hf11a4ad_0
  - numexpr=2.8.1=py37hb80d3ca_0
  - numpy=1.20.3=py37ha4e8547_0
  - numpy-base=1.20.3=py37hc2deb75_0
  - olefile=0.46=py37_0
  - openssl=1.1.1m=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h6214cd6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37hd45dc43_0
  - pip=21.2.4=py37haa95532_0
  - pluggy=1.0.0=py37haa95532_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37hd77b12b_6
  - pyreadline=2.1=py37_1
  - pyrsistent=0.18.0=py37h196d8e1_0
  - pysocks=1.7.1=py37_1
  - pytest=6.2.5=py37haa95532_2
  - pytest-cov=3.0.0=pyhd3eb1b0_0
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.2=py3.7_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py37h827c3e9_1
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyyaml=5.3.1=py37he774522_0
  - pyzmq=22.3.0=py37hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - requests=2.27.1=pyhd3eb1b0_0
  - ruamel.yaml=0.16.12=py37he774522_1
  - ruamel.yaml.clib=0.2.2=py37he774522_0
  - scipy=1.7.3=py37h0a974cb_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37haa95532_0
  - sip=4.19.13=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sphinx=4.4.0=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sqlite=3.37.2=h2bbff1b_0
  - tbb=2021.5.0=h59b6b97_0
  - terminado=0.13.1=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.7=vc14hb68737d_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py37haa95532_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - xarray=0.20.1=pyhd3eb1b0_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - yapf=0.31.0=pyhd3eb1b0_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - absl-py==1.0.0
    - cachetools==5.0.0
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - markdown==3.3.6
    - nbsphinx==0.8.8
    - nbsphinx-link==1.3.0
    - oauthlib==3.2.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sphinx-rtd-theme==1.0.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - werkzeug==2.0.3
prefix: C:\Users\321319\Miniconda3\envs\neuralhydrology
```
