### ISSUE TITLE
Trouble getting code to access GPU

### ISSUE THREAD

**Issue by chuckaustin** [neuralhydrology/neuralhydrology#76]
[Part of JOSS Review: https://github.com/https://github.com/https://github.com/openjournals/joss-reviews/issues/4050]

One other issue is that I noticed that I'm unable to use my GPU (Nvidia Quadro P520) with the library. 

I created an environment for neural hydrology on conda using environment_cuda9_2.yml. But when I try to train a model on my GPU I get an error saying pytorch was compiled without CUDA enabled.

```
2022-02-17 17:44:47,097: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\Scripts\nh-run-script.py", line 33, in <module>
    sys.exit(load_entry_point('neuralhydrology', 'console_scripts', 'nh-run')())
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\nh_run.py", line 43, in _main
    start_run(config_file=Path(args["config_file"]), gpu=args["gpu"])
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\nh_run.py", line 76, in start_run
    start_training(config)
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\training\train.py", line 22, in start_training
    trainer.initialize_training()
  File "c:\users\321319\documents\neuralhydrology\neuralhydrology\training\basetrainer.py", line 137, in initialize_training
    self.model = self._get_model().to(self.device)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 899, in to
    return self._apply(convert)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\nn\modules\rnn.py", line 182, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 593, in _apply
    param_applied = fn(param)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\nn\modules\module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\321319\Miniconda3\envs\neuralhydrology\lib\site-packages\torch\cuda\__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by kratzert** [comment]
Hi @chuckaustin 

I only know this problem if a) you installed the CPU version of PyTorch or b) PyTorch has problems detecting your GPU. Since you said you used the cuda 9.2 environment file of our library my only guess is that it has to be (b). As far as I could see from the NVIDIA homepage, your GPU should support this CUDA version. Are you sure you have an updated NVIDIA driver installed? Usually there is nothing more to do from the client side (e.g. manually installing CUDA or cudNN is not required).

However, I fear that this is not really an issue with our library and I don't know what we could do to fix this.

**Comment by kratzert** [comment]
Okay, I had another look at it. From the `conda env export` output you posted in #75  I can see that PyTorch did not install the corresponding cuda version but still the cpu version (see: `pytorch=1.10.2=py3.7_cpu_0`). I am not quite sure why this happens. I tested what happens if I create a conda env from the same environment file on my machine and I get exactly the same. Using the `environment_cuda10_2.yml` file however, I get a correctly working PyTorch installation with GPU support. I am not sure if they maybe dropped the CUDA 9.2 support.

From [here](https://pytorch.org/get-started/previous-versions/) It seems like that PyTorch 1.7.1 was the last version with CUDA 9.2 support, however our environment files seem to install PyTorch 1.10.2, which only works with CUDA 10.2 or 11.3 (see [here](https://pytorch.org/get-started/locally/)). If your GPU supports CUDA 10.2 do you mind creating and environment from the other file and testing if it works then? Seems like we should remove the 9.2 environment file.
If your GPU does not support CUDA 10.2, you could install the old PyTorch version with CUDA 9.2 support by:

```
conda install pytorch==1.7.1 cudatoolkit=9.2 -c pytorch
```
As far as I know, we do not use any features that were added recently to PyTorch so the old version should work equally fine.

**Comment by chuckaustin** [comment]
Hi @kratzert thank you for your suggestion, deleting the environment then creating it using` environment_cuda10_2.yml` got it running on my GPU, which made the training much faster. I did notice that, even on the GPU, training was much faster when I set "num_workers" to 0 instead of 8.
